#!/bin/sh

. /etc/rc.common

# Set path to Java 1.4.2
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.4.2/Home

# Set path to Parabuild installation directory
PARABUILD_HOME="{0}"

# Prepare Parabuild command
PARABUILD_COMMAND=$PARABUILD_HOME/bin/parabuild.sh
[ -f $PARABUILD_COMMAND ] || exit 2

StartService ()
'{'
	ConsoleMessage '"Starting Parabuild server"'
	su -m parabuild -c "$PARABUILD_COMMAND start"
'}'

StopService ()
'{'
	ConsoleMessage '"Stopping Parabuild server"'
  su -m parabuild -c "$PARABUILD_COMMAND stop"
'}'

RestartService ()
'{'
	ConsoleMessage '"Restarting Parabuild server"'
  su -m parabuild -c "$PARABUILD_COMMAND restart"
'}'

RunService "$1"
